# Generated by Django 5.2.6 on 2025-09-26 04:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('interval', models.IntegerField(default=0)),
                ('ease_factor', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.30')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('streak', models.IntegerField(default=0)),
                ('lapses', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review'), ('lapsed', 'Lapsed')], default='new', max_length=20)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='core.deck')),
            ],
        ),
    ]
